package:
    name: alexandria 
    version: "2.14.1"

source:
    git_rev: 2.14.1
    git_url: https://github.com/astrorama/Alexandria.git

build:
  number: 3

requirements:
    build:
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
    host:
        - elements ==5.8
        - boost-cpp ==1.70
        - cfitsio
        - CCfits
        - python
        - pytest
    run:
        - elements ==5.8
        - boost-cpp ==1.70
        - cfitsio
        - CCfits

about:
    home: https://github.com/astrorama/Alexandria.git
    license: LGPL
    license_file: LICENSE
    summary: SDC-CH common library for the Euclid project

