{% set name = "Alexandria" %}
{% set version = "2.27.0" %}
{% set build_number = 1 %}

package:
    name: {{ name|lower }}
    version: {{ version }} 

source:
    git_rev: {{ version }}
    git_url: https://github.com/astrorama/Alexandria.git

build:
    number: {{ build_number }}
    run_exports:
      - {{ pin_subpackage('alexandria', max_pin='x.x.x') }}

requirements:
    build:
        - python                             # [build_platform != target_platform]
        - cross-python_{{ target_platform }} # [build_platform != target_platform]
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
    host:
        - python
        - boost
        - elements ==6.0.1
        - cfitsio >=3.470
        - CCfits >=2.5
    run:
        - {{ pin_compatible('python', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('boost', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('cfitsio', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('CCfits', min_pin='x.x', max_pin='x.x') }}

test:
    commands:
        - $PREFIX/bin/AlexandriaVersion

about:
    home: https://github.com/astrorama/Alexandria.git
    license: LGPL
    license_file: LICENSE
    summary: SDC-CH common library for the Euclid project

