package:
    name: alexandria 
    version: "2.17.1"

source:
    git_rev: "2.17.1"
    git_url: https://github.com/astrorama/Alexandria.git

build:
  number: 3
  run_exports:
    - {{ pin_subpackage('alexandria', max_pin='x.x.x') }}

requirements:
    build:
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
    host:
        - elements ==5.10
        - boost-cpp ==1.70
        - cfitsio >=3.470
        - CCfits >=2.5
        - python >=3.7
        - pytest >=5.0.0
    run:
        - boost-cpp ==1.70
        - {{ pin_compatible('CCfits') }}

about:
    home: https://github.com/astrorama/Alexandria.git
    license: LGPL
    license_file: LICENSE
    summary: SDC-CH common library for the Euclid project

