{% set name = "Alexandria" %}
{% set version = "2.19" %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
    name: {{ name|lower }}
    version: {{ version }} 

source:
    git_rev: develop 
    git_url: https://github.com/astrorama/Alexandria.git

build:
    number: {{ build_number }}
    run_exports:
      - {{ pin_subpackage('alexandria', max_pin='x.x.x') }}

requirements:
    build:
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - python                             # [build_platform != target_platform]
        - cross-python_{{ target_platform }} # [build_platform != target_platform]
    host:
        - python
        - boost-cpp
        - elements ==5.12
        - cfitsio >=3.470
        - CCfits >=2.5
    run:
        - {{ pin_compatible('python', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('boost-cpp', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('cfitsio') }}
        - {{ pin_compatible('CCfits') }}

test:
    commands:
        - $PREFIX/bin/AlexandriaVersion

about:
    home: https://github.com/astrorama/Alexandria.git
    license: LGPL
    license_file: LICENSE
    summary: SDC-CH common library for the Euclid project

