package:
    name: alexandria 
    version: "2.17.1"

source:
    git_rev: "2.17.1"
    git_url: https://github.com/astrorama/Alexandria.git
    patches:
      - AlexandriaVersion.patch

build:
    number: 4
    run_exports:
      - {{ pin_subpackage('alexandria', max_pin='x.x.x') }}

test:
    commands:
        - $PREFIX/bin/AlexandriaVersion

requirements:
    build:
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
    host:
        - python ==3.8
        - boost-cpp ==1.73
        - elements ==5.10
        - cfitsio >=3.470
        - CCfits >=2.5
    run:
        - {{ pin_compatible('python', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('boost-cpp', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('cfitsio') }}
        - {{ pin_compatible('CCfits') }}

about:
    home: https://github.com/astrorama/Alexandria.git
    license: LGPL
    license_file: LICENSE
    summary: SDC-CH common library for the Euclid project

